// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBujirUa7RubC_W9UhUk9RGZ97-fyAhm7o',
    appId: '1:690210712354:web:01b8e796b494f257a1937b',
    messagingSenderId: '690210712354',
    projectId: 'dentalauth-1ad0b',
    authDomain: 'dentalauth-1ad0b.firebaseapp.com',
    storageBucket: 'dentalauth-1ad0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDefbKj_vNjYWPTJnVcKLm6fp2aWJ2Wjs',
    appId: '1:690210712354:android:6d636cf963adad58a1937b',
    messagingSenderId: '690210712354',
    projectId: 'dentalauth-1ad0b',
    storageBucket: 'dentalauth-1ad0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANnQxtfdMkdTbv9evwV32LyfLezdo3LGs',
    appId: '1:690210712354:ios:e31dfb24dc9f4a3fa1937b',
    messagingSenderId: '690210712354',
    projectId: 'dentalauth-1ad0b',
    storageBucket: 'dentalauth-1ad0b.appspot.com',
    iosClientId: '690210712354-hd0t98tdkh1r0su07v8tq2q419skp820.apps.googleusercontent.com',
    iosBundleId: 'com.example.dentalMinor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANnQxtfdMkdTbv9evwV32LyfLezdo3LGs',
    appId: '1:690210712354:ios:e31dfb24dc9f4a3fa1937b',
    messagingSenderId: '690210712354',
    projectId: 'dentalauth-1ad0b',
    storageBucket: 'dentalauth-1ad0b.appspot.com',
    iosClientId: '690210712354-hd0t98tdkh1r0su07v8tq2q419skp820.apps.googleusercontent.com',
    iosBundleId: 'com.example.dentalMinor',
  );
}
